/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateThumbnailsRouteImport } from './routes/api/generate-thumbnails'
import { Route as ApiGenerateScriptRouteImport } from './routes/api/generate-script'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateThumbnailsRoute = ApiGenerateThumbnailsRouteImport.update({
  id: '/api/generate-thumbnails',
  path: '/api/generate-thumbnails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateScriptRoute = ApiGenerateScriptRouteImport.update({
  id: '/api/generate-script',
  path: '/api/generate-script',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/generate-thumbnails': typeof ApiGenerateThumbnailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/generate-thumbnails': typeof ApiGenerateThumbnailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/studio': typeof StudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/generate-thumbnails': typeof ApiGenerateThumbnailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/studio'
    | '/api/chat'
    | '/api/generate-script'
    | '/api/generate-thumbnails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/studio'
    | '/api/chat'
    | '/api/generate-script'
    | '/api/generate-thumbnails'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/studio'
    | '/api/chat'
    | '/api/generate-script'
    | '/api/generate-thumbnails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  StudioRoute: typeof StudioRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateScriptRoute: typeof ApiGenerateScriptRoute
  ApiGenerateThumbnailsRoute: typeof ApiGenerateThumbnailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-thumbnails': {
      id: '/api/generate-thumbnails'
      path: '/api/generate-thumbnails'
      fullPath: '/api/generate-thumbnails'
      preLoaderRoute: typeof ApiGenerateThumbnailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-script': {
      id: '/api/generate-script'
      path: '/api/generate-script'
      fullPath: '/api/generate-script'
      preLoaderRoute: typeof ApiGenerateScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  StudioRoute: StudioRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateScriptRoute: ApiGenerateScriptRoute,
  ApiGenerateThumbnailsRoute: ApiGenerateThumbnailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
